changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Performance
      labels:
        - perf
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
        - test
